# Builds Xlet.Wallet software

language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

before_install:
  - cd Xlet.Wallet

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio run
